### ISSUE TITLE
Add handlesnull parameter to @qgsfunction

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2772]
Original commit: https://github.com/qgis/QGIS/commit/773138cf57bd8537888766de556b7ff38e8107e2 by m-kuhn

Up to date it was not possible to create a function that handles NULL values with the
@qgsfunction decorator. As soon as any parameter was NULL, the return value would also
be NULL.

Example of a function that returns a value now with a NULL paramter and would have returned NULL before

```
@qgsfunction(args=-1, group='Custom', handlesnull=True)
def mean_value(vals, feature, parent):
    valid_vals = [val for val in vals if val != NULL]
    return sum(valid_vals)/len(valid_vals)
```

[FEATURE]

**Comment by DelazJ** [comment]
we do not go into details for this functionality so i'm not sure we need to document this

**Comment by SrNetoChan** [comment]
We talk about custom functions in here. Maybe we can add this nullhandler to the example.

https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html?highlight=function#function-editor

**Comment by DelazJ** [comment]
> We talk about custom functions in here.

Yeah, got some details only a couple of weeks ago, with a higher screenshots with params so we could update the screenshot with [handlesnull description](https://github.com/qgis/QGIS/pull/7813). For the sample code itself, I don't really know and have some questions.

@m-kuhn In the Python console, a function like the following one naturally returns valid results given that valid_vals filters out null values and calculations are done on the valid_vals list, doesn't it ? 
```python
def mean_value(vals):
    valid_vals = [val for val in vals if val != NULL]
    return sum(valid_vals)/len(valid_vals)
```
So why does the next one need a particular parameter to handle those null values? Was that a bug?
```python
@qgsfunction(args=-1, group='Custom', handlesnull=True)
def mean_value(vals, feature, parent):
    valid_vals = [val for val in vals if val != NULL]
    return sum(valid_vals)/len(valid_vals)
```
I mean why does it still return null (without the `handlesnull=True`) though those null values should not be in the calculations? IOW I'd have expected the code to be something like below (where null values are magically ignored any time the vals list is called):
```python
@qgsfunction(args=-1, group='Custom', handlesnull=True)
def mean_value(vals, feature, parent):
    return sum(vals)/len(vals)
```

**Comment by m-kuhn** [comment]
with `handlesnull=False` (default) it will just always return `NULL`.

With `handlesnull=True` we want to disable any magic and know inside the function, if `NULL` has been passed as a parameter (and at which position). We told the expression function that we want `NULL` and we will take care of handling it carefully.

If we do not handle it (your last example), this is what happens:

```
sum([1,2,NULL])
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'QVariant'
```
