### ISSUE TITLE
Explain how to test iface in PyQGIS testing framework

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3776]
## Description

As per https://github.com/qgis/QGIS-Documentation/pull/3621#issuecomment-496475861
One question.
How can I make it detect iface, without generating a standlone application or my own iface?

 ```
 from qgis.utils import iface

   iface.mapCanvas().layers()
Exception raised:
   Traceback (most recent call last):
     File "/usr/lib/python3.6/doctest.py", line 1330, in __run
       compileflags, 1), test.globs)
     File "<doctest default[0]>", line 3, in <module>
       iface.mapCanvas().layers()
   AttributeError: 'NoneType' object has no attribute 'mapCanvas'

```
and processing too:

`ModuleNotFoundError: No module named 'processing'`

Currently code samples making these calls are made untested, hence potentially not reliable in the long run

**Comment by All4Gis** [comment]
Any updates on this @DelazJ ?

**Comment by DelazJ** [comment]
Euhhh... Unfortunately, none!
I don't have the necessary background to look into this issue so nothing would come from me. Since this is an issue we'll face if we want to have the testing infrastructure fully operational, the report was to attract skilled people. But seems that it fails...
Sorry.
