### ISSUE TITLE
bootstrap.py doesn't work with modern versions of Pip

### ISSUE THREAD

**Issue by daviewales** [qgis/QGIS-Documentation#4622]
## Description

I am attempting to build the documentation using the instructions from the Readme.
Running `python bootstrap.py` yields the following `pip` error:

```
Running virtualenv with interpreter /usr/local/bin/python
New python executable in /Users/dwales/Documents/Reference/Mapping/QGIS-Documentation/virtualenv/bin/python2.7
Also creating executable in /Users/dwales/Documents/Reference/Mapping/QGIS-Documentation/virtualenv/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /Users/dwales/Docume...ualenv/bin/python2.7 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
AttributeError: 'module' object has no attribute 'main'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "bootstrap.py", line 2399, in <module>
    main()
  File "bootstrap.py", line 726, in main
    symlink=options.symlink)
  File "bootstrap.py", line 994, in create_environment
    download=download,
  File "bootstrap.py", line 924, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "bootstrap.py", line 819, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/dwales/Docume...ualenv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

This [appears to be due to a change](https://github.com/pypa/pip/issues/5240#issuecomment-381662679) in `pip`. Specifically, `pip.main` was moved to `pip._internal.main`, to indicate that calling `pip.main` was not a supported way of using `pip`.

The [officially supported method](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program) of using `pip` from within a Python script is to use `subprocess`.

I understand that the `bootstrap.py` file is generated by `Paver`, but I was unable to figure out how to use Paver to generate a new `bootstrap.py` file.

The following diff shows the changes I made to `bootstrap.py` which enabled me to build the docs:

```
diff --git a/bootstrap.py b/bootstrap.py
index 25179ca..a9ea7b6 100644
--- a/bootstrap.py
+++ b/bootstrap.py
@@ -881,7 +881,9 @@ def install_wheel(project_names, py_executable, search_dirs=None,
         import tempfile
         import os
 
-        import pip
+        #import pip
+        import sys
+        import subprocess
 
         #cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
         cert_data = None
@@ -898,7 +900,11 @@ def install_wheel(project_names, py_executable, search_dirs=None,
                 args += ["--cert", cert_file.name]
             args += sys.argv[1:]
 
-            sys.exit(pip.main(args))
+            #sys.exit(pip.main(args))
+            subprocess.check_call([sys.executable, '-m', 'pip'] + args)
+            sys.exit()
+        except subprocess.CalledProcessError as err:
+            sys.exit(err.returncode)
         finally:
             if cert_file is not None:
                 os.remove(cert_file.name)
@@ -978,7 +984,7 @@ def create_environment(home_dir, site_packages=False, clear=False,
 
     if not no_setuptools:
         to_install.append('setuptools')
-        to_install.append('pkg_resources')
+        #to_install.append('pkg_resources')
 
     if not no_pip:
         to_install.append('pip')
```

However, this is obviously not the correct solution, as `bootstrap.py` is a generated file.

OS: macOS 10.13.6
Python: 'brewed' 2.7.17 and 'brewed' 3.7.5. Also tried default macOS python 2.7.10
Page URL: https://github.com/qgis/QGIS-Documentation#building-the-documentation-using-paver

**Comment by DelazJ** [comment]
@daviewales We have removed the paver method from instructions and the current process works pretty well on macos (would you want to give it a try).
I suggest we close this report. Thanks
